### ISSUE TITLE
[SOPT] 세미나 1주차 실습과제_은행 프로그램 설계하기

### ISSUE THREAD

**Issue by junggyo1020** [NOW-SOPT-SERVER/junggyo1020#3]
# ⚙️ ISSUE
- 은행프로그램 설계하기

# 📄 To-Do
- [x] 도메인 설계
- [x] 계좌 생성하기 기능 구현
- [x] 입금하기 구현
- [x] 출금하기 구현
- [x] 다른 계좌로 이체하기 구현
- [x] 잔액 조회하기 구현
