### ISSUE TITLE
[SOPT] 세미나 2주차 실습과제_멤버 리스트 반환 API 만들기

### ISSUE THREAD

**Issue by junggyo1020** [NOW-SOPT-SERVER/junggyo1020#7]
# ⚙️ ISSUE
- 등록한 모든 멤버가 List로 반환되는 API를 구현

# 📄 To-Do
- [x] MemberService 클래스에 메소드 추가
- [x] MemberController 클래스에 API 엔드포인트 추가
- [x] Postman으로 생성 테스트
